name: Backend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - "!backend/**/*.MD"
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: |
          REVISION=$(make backend-version)
          BUILD_DATE=$(date -u +"%Y%m%d%H%M")
          VERSION="${REVISION}.${BUILD_DATE}"
          echo "Building backend version: ${VERSION}"
          make backend GOAL=deploy VERSION="${VERSION}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}