---
apiVersion: v1
kind: Secret
metadata:
  name: ${service.name}
  namespace: ${solution.name}
type: Opaque
data:
  mongo.username: ${mongo.username}
  mongo.password: ${mongo.password}
  gemini.apiKey: ${gemini.apiKey}