// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static const String androidServerClientId =
      '159272058870-i83mdabckc9nb1mlh2mk9ac3ub03ej83.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpG-Kl72JOZRl7cDFbHwtm0dMpy5_PAOo',
    appId: '1:159272058870:android:4ebc3f9702d7d5eed711d7',
    messagingSenderId: '159272058870',
    projectId: 'bitapp-442618',
    storageBucket: 'bitapp-442618.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWa_0GN8PJyX0uQoI4chXvMUu_WjPZdZU',
    appId: '1:925204357438:ios:701109659f72b2a47c4c6f',
    messagingSenderId: '925204357438',
    projectId: 'bitapp-cortech',
    storageBucket: 'bitapp-cortech.firebasestorage.app',
    androidClientId:
        '925204357438-087d8qc9dcf6i3t3ci1i2u2tcb5tot47.apps.googleusercontent.com',
    iosClientId:
        '925204357438-n42h400avbdv3bcoi3qgrd2mbl6t2hud.apps.googleusercontent.com',
    iosBundleId: 'io.dkakunsi.bitapp',
  );
}
