name: Backend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - "!backend/**/*.MD"
  workflow_dispatch:
    inputs:
      deploy_only:
        description: "Just Deploy"
        required: false
        type: boolean
        default: false
      version:
        description: "Version to deploy"
        required: false
        type: string

jobs:
  build:
    if: ${{ !github.event.inputs.deploy_only }}
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version.outputs.version }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - name: Compute version
        id: version
        run: |
          VERSION=$(make backend-version)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "25"
          distribution: "temurin"
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        run: make backend GOAL=deploy VERSION="${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release Helm Chart
        run: make backend-chart TOKEN="${{ secrets.HELM_CHARTS_TOKEN }}" VERSION="${{ steps.version.outputs.version }}"

      ## Since GCP Cloud Run doesn't support private registries, we need to push the image to Docker Hub as well
      - name: Docker Hub - Prepare artifacts
        run: |
          mkdir -p ./dockerhub/maven
          cp ./backend/app/target/app.jar ./dockerhub/maven/
          cp ./backend/app/target/Dockerfile ./dockerhub/
      - name: Docker Hub - Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Hub - Build and Push
        uses: docker/build-push-action@v5
        with:
          context: ./dockerhub
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bitapp:${{ steps.version.outputs.version }}

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    if: ${{ always() && (needs.build.result == 'success' || github.event.inputs.deploy_only == 'true') }}
    env:
      VERSION: ${{ github.event.inputs.deploy_only == 'true' && github.event.inputs.version || needs.build.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: bitapp
          image: docker.io/dkakunsi/bitapp:${{ env.VERSION }}
          region: asia-southeast2
          allow_unauthenticated: true
          port: 8080
          service_account: ${{ vars.GCP_SA }}
          env_vars: |-
            app.port=${{ vars.APP_PORT }}
            JWK_URL=${{ vars.JWK_URL }}
            MONGO_DATABASE=${{ vars.MONGO_DATABASE_NAME }}
            MONGO_SECURE=${{ vars.MONGO_SECURE }}
            MONGO_CONNECTION_STRING=${{ secrets.MONGO_CONNECTION_STRING_DEV }}
            MONGO_USERNAME=${{ secrets.MONGO_USERNAME_DEV }}
            MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD_DEV }}
            GEMINI_API_KEY=${{ secrets.AI_GEMINI_APIKEY }}
            GEMINI_MODEL_NAME=${{ vars.AI_GEMINI_MODELNAME }}
          env_vars_update_strategy: overwrite
          min_instances: 0
          max_instances: 5
